#!/bin/sh
# postrm script for kamailio

set -e

removal_wrapper() {
  # remove the init script only on ce systems, as
  # the pro system handles it inside the monitoring/HA setup
  if ! [ -x "$(which ngcp-check_active 2>/dev/null)" ]; then
    update-rc.d kamailio-lb    remove >/dev/null
    update-rc.d kamailio-proxy remove >/dev/null
  fi
}

if [ "$1" = "purge" ] ; then
  removal_wrapper
fi

exit 0

#DEBHELPER#
